# Organization or user who owns this repo
owner: Aspire-Impact          # ✅ Must match exactly (case-sensitive)
repo: upptime-monitor         # ✅ Your repo name

sites:
  - name: Ikoo Website
    url: https://www.ikooworld.com
    checkDns: true          # ✅ enables DNS resolution check
    checkSsl: true 
  - name: User Portal
    url: https://platform.ikooworld.com/
    checkDns: true          # ✅ enables DNS resolution check
    checkSsl: true 
  - name: Admin Portal
    url: https://admin.ikooworld.com/
    checkDns: true          # ✅ enables DNS resolution check
    checkSsl: true 
  - name: Assurara Portal
    url: https://assurance.ikooworld.com/
    checkDns: true          # ✅ enables DNS resolution check
    checkSsl: true 
  - name: Backend Service
    url: https://api.ikooworld.com/
    checkDns: true          # ✅ enables DNS resolution check
    checkSsl: true 
    expectedStatusCodes:
      - 404

status-website:
  baseUrl: /upptime-monitor    # ✅ Correct for aspire-impact.github.io/upptime-monitor
  name: Aspire Impact Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Monitoring uptime and performance of Aspire Impact applications and APIs."
  navbar:
    - title: Status
      href: /
